# Generated by Django 4.2.3 on 2023-07-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
