# Generated by Django 4.2.3 on 2023-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0002_remove_contact_content_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
